FROM vllm/vllm-openai:v0.18.0

RUN sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list \
    && sed -i 's@//.*security.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y build-essential

RUN pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/simple

WORKDIR /app
COPY dockerfiles/start-vllm.sh /app/
RUN chmod +x /app/start-vllm.sh

ENTRYPOINT []

CMD ["/app/start-vllm.sh"]
