FROM pytorch/pytorch:2.10.0-cuda13.0-cudnn9-runtime

RUN sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list \
    && sed -i 's@//.*security.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y build-essential

RUN pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/simple

RUN git clone https://kkgithub.com/vllm-project/vllm.git /tmp/vllm \
    && cd /tmp/vllm \
    && python use_existing_torch.py \
    && pip install -r requirements/build.txt \
    && pip install --no-build-isolation -e . \
    && rm -rf /tmp/vllm

WORKDIR /app
COPY dockerfiles/start-vllm.sh /app/
RUN chmod +x /app/start-vllm.sh

CMD ["/app/start-vllm.sh"]
