FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime

RUN sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list \
    && apt-get update && apt-get install -y \
    build-essential

RUN pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/simple \
    && pip install vllm

WORKDIR /app
COPY dockerfiles/start-vllm.sh /app/
RUN chmod +x /app/start-vllm.sh

CMD ["/app/start-vllm.sh"]
