import re
import warnings
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, model_validator
from typing import Any, Callable, Dict, List, Optional, Union

from evalscope.api.metric.semantics import MetricIdentity
from evalscope.utils.logger import get_logger

logger = get_logger()

Value = Dict[str, Union[int, float, bool]]


class Score(BaseModel):
    """Score generated by a scorer."""

    value: Value = Field(default_factory=dict)
    """Score value as a dictionary. Key is the score name, value is the score value.
    The first key is considered the main score by default."""

    extracted_prediction: Optional[str] = Field(default=None)
    """Answer extracted from model output (optional)"""

    prediction: Optional[str] = Field(default=None)
    """Original prediction text from the model (optional)"""

    explanation: Optional[str] = Field(default=None)
    """Explanation of score (optional)."""

    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)
    """Additional metadata related to the score"""

    main_score_name: Optional[str] = Field(default=None)
    """Raw per-sample score name used by :attr:`main_value` in a multi-score result.

    This selects a value inside one ``Score`` only. ``BenchmarkMeta.primary_metric`` is the
    report-level declaration; this field does not assign report metric roles.
    """

    @property
    def main_value(self) -> Union[int, float, bool]:
        """Main score value."""
        if self.main_score_name and self.main_score_name in self.value:
            return self.value[self.main_score_name]
        elif self.value:
            # If main_score_name is not set or not found, use the first value and update main_score_name
            first_key = next(iter(self.value))
            self.main_score_name = first_key
            return self.value[first_key]
        return None

    @main_value.setter
    def main_value(self, value: Union[int, float, bool]):
        """Set the main score value."""
        if self.main_score_name:
            # If main_score_name is already set, use it
            self.value[self.main_score_name] = value
        elif self.value:
            # If no main_score_name but value dict exists, use the first key
            first_key = next(iter(self.value))
            self.main_score_name = first_key
            self.value[first_key] = value
        else:
            # If neither main_score_name nor value dict exists, initialize both
            self.main_score_name = 'default'
            self.value[self.main_score_name] = value


class SampleScore(BaseModel):
    """Score for a Sample."""

    score: Score
    """A score"""

    sample_id: Optional[Union[str, int]] = Field(default=None)
    """A sample id"""

    group_id: Optional[Union[str, int]] = Field(default=None)
    """A group id for the sample, used for grouping k repeated samples."""

    sample_metadata: Optional[Dict[str, Any]] = Field(default=None)
    """Metadata from the sample"""


class AggScore(BaseModel):
    """Output of an aggregation operation."""

    model_config = ConfigDict(populate_by_name=True, extra='forbid')

    score: float = Field(default=0.0)
    """Aggregated value as a float."""

    metric_name: str = Field(default='')
    """Name of the metric being aggregated."""

    aggregation: str = Field(validation_alias=AliasChoices('aggregation', 'aggregation_name'))
    """Canonical name of the aggregation method. It is not part of ``metric_name``."""

    dimensions: Dict[str, Union[str, int, float, bool]] = Field(default_factory=dict)
    """Structured axes such as scope, threshold, level, target, or k."""

    num: int = Field(default=0)
    """Number of samples used in the aggregation."""

    ids: Optional[List[Union[str, int]]] = Field(default=None)
    """List of sample IDs used in the aggregation, if applicable."""

    metadata: Optional[Dict[str, Any]] = Field(default=None)
    """Additional metadata related to the aggregation."""

    @property
    def identity(self) -> MetricIdentity:
        """Return the canonical structured identity represented by this aggregate."""
        return MetricIdentity(name=self.metric_name, aggregation=self.aggregation, dimensions=self.dimensions)

    @model_validator(mode='before')
    @classmethod
    def _warn_deprecated_aggregation_name(cls, data: Any) -> Any:
        if isinstance(data, dict) and 'aggregation_name' in data and 'aggregation' not in data:
            warnings.warn('AggScore.aggregation_name is deprecated; use aggregation.', DeprecationWarning, stacklevel=3)
        return data

    @model_validator(mode='after')
    def _normalize_legacy_identity_fields(self) -> 'AggScore':
        """Normalize known adapter aliases before an aggregate leaves the metric layer."""
        from evalscope.metrics.semantics.catalog import LEGACY_METRIC_MIGRATIONS
        from evalscope.metrics.semantics.identity import migrate_legacy_identity

        canonical_pattern = re.compile(r'^[a-z][a-z0-9_]*$')
        known_dynamic = re.fullmatch(
            r'.+_(?:pass|vote)@\d+|.+_pass\^\d+|(?:mean_)?ACC@\d+(?:\.\d+)?|(?:mean_)?Bleu_\d+',
            self.metric_name,
        )
        if (
            not canonical_pattern.fullmatch(self.metric_name) and self.metric_name not in LEGACY_METRIC_MIGRATIONS
            and not known_dynamic
        ):
            raise ValueError(
                f'unknown non-canonical metric_name={self.metric_name!r}; declare a legacy migration or use snake_case'
            )

        identity = migrate_legacy_identity(self.metric_name, self.aggregation, self.dimensions)
        if (self.metric_name, self.aggregation, self.dimensions) != (
            identity.name,
            identity.aggregation,
            identity.dimensions,
        ):
            warnings.warn(
                f"legacy metric identity '{self.metric_name}' is deprecated; emit {identity.key}",
                DeprecationWarning,
                stacklevel=3,
            )
        self.metric_name = identity.name
        self.aggregation = identity.aggregation
        self.dimensions = identity.dimensions
        return self


class Aggregator:

    name = 'default'

    def __call__(self, scores: List[SampleScore]) -> List[AggScore]:
        r"""Aggregate a metric on a list of scores.

        Args:
          scores: List of scores.

        Returns:
          List[AggregatOutput]: List of aggregated outputs.
        """
        ...
