import warnings
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, model_validator
from typing import Any, Callable, Dict, List, Optional, Union

from evalscope.api.metric.semantics import MetricIdentity
from evalscope.constants import ScoreStatus

Value = Dict[str, Union[int, float, bool]]


class JudgeSummary(BaseModel):
    """First-class summary of a judge session, for reports and offline inspection."""

    status: ScoreStatus = Field(default=ScoreStatus.SUCCESS)
    """Whether scoring completed, degraded, or was unavailable."""

    scored: int = Field(default=0)
    """Samples with a usable score in this summary's scope (one for a sample summary)."""

    total: int = Field(default=1)
    """Samples considered in this summary's scope."""

    coverage: float = Field(default=0.0)
    """``scored / total``; unavailable samples are reported as zero coverage, not score zero."""

    judge_models: List[str] = Field(default_factory=list)
    """Judge model ids that produced this score."""

    valid_observations: int = Field(default=0)
    """Observations that yielded a usable verdict."""

    total_observations: int = Field(default=0)
    """Observations attempted, including invalid ones."""

    failures: Dict[str, int] = Field(default_factory=dict)
    """Failure counts keyed by :class:`ScoreStatus` value."""

    disagreement: Dict[str, Any] = Field(default_factory=dict)
    """Typed disagreement statistics; distinct from execution degradation."""

    error: Optional[str] = Field(default=None)
    """Human-readable reason the score is unavailable, if any."""

    fingerprint: Optional[str] = Field(default=None)
    """Semantic review-cache fingerprint used for this score."""

    provenance: Dict[str, Any] = Field(default_factory=dict)
    """Execution settings that affect whether this is an official benchmark score."""


class Score(BaseModel):
    """Score generated by a scorer."""

    value: Value = Field(default_factory=dict)
    """Score value as a dictionary. Key is the score name, value is the score value.
    The first key is considered the main score by default."""

    status: ScoreStatus = Field(default=ScoreStatus.SUCCESS)
    """Whether this score is usable. A non-usable status means the affected metric keys are
    omitted from :attr:`value` and the sample drops out of aggregation instead of scoring 0."""

    judge_summary: Optional[JudgeSummary] = Field(
        default=None,
        validation_alias=AliasChoices('judge_summary', 'judge_detail'),
    )
    """Judge execution summary, populated only when an LLM judge produced this score."""

    extracted_prediction: Optional[str] = Field(default=None)
    """Answer extracted from model output (optional)"""

    prediction: Optional[str] = Field(default=None)
    """Original prediction text from the model (optional)"""

    explanation: Optional[str] = Field(default=None)
    """Explanation of score (optional)."""

    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)
    """Additional metadata related to the score"""

    main_score_name: Optional[str] = Field(default=None)
    """Raw per-sample score name used by :attr:`main_value` in a multi-score result.

    This selects a value inside one ``Score`` only. ``BenchmarkMeta.primary_metric`` is the
    report-level declaration; this field does not assign report metric roles.
    """

    @property
    def judge_detail(self) -> Optional[JudgeSummary]:
        """Deprecated Python compatibility alias for :attr:`judge_summary`."""
        return self.judge_summary

    @judge_detail.setter
    def judge_detail(self, value: Optional[JudgeSummary]) -> None:
        self.judge_summary = value

    @property
    def main_value(self) -> Union[int, float, bool]:
        """Main score value."""
        if self.main_score_name and self.main_score_name in self.value:
            return self.value[self.main_score_name]
        elif self.value:
            # If main_score_name is not set or not found, use the first value and update main_score_name
            first_key = next(iter(self.value))
            self.main_score_name = first_key
            return self.value[first_key]
        return None

    @main_value.setter
    def main_value(self, value: Union[int, float, bool]):
        """Set the main score value."""
        if self.main_score_name:
            # If main_score_name is already set, use it
            self.value[self.main_score_name] = value
        elif self.value:
            # If no main_score_name but value dict exists, use the first key
            first_key = next(iter(self.value))
            self.main_score_name = first_key
            self.value[first_key] = value
        else:
            # If neither main_score_name nor value dict exists, initialize both
            self.main_score_name = 'default'
            self.value[self.main_score_name] = value


class SampleScore(BaseModel):
    """Score for a Sample."""

    score: Score
    """A score"""

    sample_id: Optional[Union[str, int]] = Field(default=None)
    """A sample id"""

    group_id: Optional[Union[str, int]] = Field(default=None)
    """A group id for the sample, used for grouping k repeated samples."""

    generation_index: Optional[int] = Field(default=None)
    """Planned zero-based generation position inside ``group_id``; never compact missing attempts."""

    sample_metadata: Optional[Dict[str, Any]] = Field(default=None)
    """Metadata from the sample"""


class AggScore(BaseModel):
    """Output of an aggregation operation."""

    model_config = ConfigDict(populate_by_name=True, extra='forbid')

    score: float = Field(default=0.0)
    """Aggregated value as a float."""

    metric_name: str = Field(default='')
    """Name of the metric being aggregated."""

    aggregation: str = Field(default='identity', validation_alias=AliasChoices('aggregation', 'aggregation_name'))
    """Canonical name of the aggregation method. It is not part of ``metric_name``."""

    dimensions: Dict[str, Union[str, int, float, bool]] = Field(default_factory=dict)
    """Structured axes such as scope, threshold, level, target, or k."""

    num: int = Field(default=0)
    """Number of samples used in the aggregation."""

    ids: Optional[List[Union[str, int]]] = Field(default=None)
    """List of sample IDs used in the aggregation, if applicable."""

    metadata: Optional[Dict[str, Any]] = Field(default=None)
    """Additional metadata related to the aggregation."""

    @property
    def identity(self) -> MetricIdentity:
        """Return the canonical structured identity represented by this aggregate."""
        return MetricIdentity(name=self.metric_name, aggregation=self.aggregation, dimensions=self.dimensions)

    @property
    def aggregation_name(self) -> str:
        """Deprecated compatibility alias for :attr:`aggregation`."""
        warnings.warn('AggScore.aggregation_name is deprecated; use aggregation.', DeprecationWarning, stacklevel=2)
        return self.aggregation

    @model_validator(mode='before')
    @classmethod
    def _warn_deprecated_aggregation_name(cls, data: Any) -> Any:
        if isinstance(data, dict) and 'aggregation_name' in data and 'aggregation' not in data:
            warnings.warn('AggScore.aggregation_name is deprecated; use aggregation.', DeprecationWarning, stacklevel=3)
        return data

    @model_validator(mode='after')
    def _canonicalize_identity_fields(self) -> 'AggScore':
        """Normalize producer syntax without assigning legacy semantics."""
        from evalscope.metrics.semantics.identity import canonicalize_producer_identity

        identity = canonicalize_producer_identity(self.metric_name, self.aggregation, self.dimensions)
        self.metric_name = identity.name
        self.aggregation = identity.aggregation
        self.dimensions = identity.dimensions
        return self


class Aggregator:

    name = 'default'

    def __call__(self, scores: List[SampleScore]) -> List[AggScore]:
        r"""Aggregate a metric on a list of scores.

        Args:
          scores: List of scores.

        Returns:
          List[AggregatOutput]: List of aggregated outputs.
        """
        ...
