version: '3.8'

services:
  vllm-service:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile_vllm
    # image: deploy-vllm-service:latest
    container_name: vllm-service
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_PATH=${MODEL_PATH_PREFIX}/${MODEL_NAME}
      - VLLM_HOST=${VLLM_HOST}
      - VLLM_PORT=${VLLM_PORT}
      - VLLM_DTYPE=${VLLM_DTYPE}
      - VLLM_MAX_MODEL_LEN=${VLLM_MAX_MODEL_LEN}
      - VLLM_TENSOR_PARALLEL_SIZE=${VLLM_TENSOR_PARALLEL_SIZE}
      - VLLM_GPU_MEMORY_UTILIZATION=${VLLM_GPU_MEMORY_UTILIZATION}
    volumes:
      - /data/pretrained_models:/data/pretrained_models
    ports:
      - "${VLLM_PORT}:${VLLM_PORT}"
    networks:
      - eval-network
    devices:
      - "nvidia.com/gpu=all"

  eval-service:
    build:
      context: ~/evalscope
      dockerfile: deploy/dockerfiles/Dockerfile_eval
    # image: deploy-eval-service:latest
    container_name: eval-service-offline
    environment:
      - EVAL_MODEL_NAME=${MODEL_NAME}
      - EVAL_API_URL=${EVAL_API_URL}
      - EVAL_API_KEY=${EVAL_API_KEY}
      - EVAL_DATASETS=${EVAL_DATASETS}
      - EVAL_TYPE=${EVAL_TYPE}
      - EVAL_LIMIT=${EVAL_LIMIT}
      - EVAL_MAX_TOKENS=${EVAL_MAX_TOKENS}
      - VLLM_PORT=${VLLM_PORT}
    networks:
      - eval-network

networks:
  eval-network:
    driver: bridge
