/* ═══════════════════════════════════════════════════════════════════
 * i18n dictionary — Performance Benchmark Report
 *
 * Keys follow a dot-notation namespace:
 *   toc.*       — floating table of contents
 *   nav.*       — TOC link labels
 *   header.*    — page header text
 *   meta.*      — header meta-chip labels
 *   section.*   — section heading titles
 *   card.*      — card / sub-card heading titles
 *   badge.*     — inline count suffixes ("runs", "requests")
 *   footer.*    — footer text
 *   <tab label> — dynamic tab labels injected by Python/Jinja2
 *                 (keys must match the `label` field produced by
 *                  generate_report.py and perf_charts.py exactly)
 *
 * To add a new language, duplicate the `en` block, change the key,
 * and provide translated values. No other code changes are required.
 * ═══════════════════════════════════════════════════════════════════ */
var I18N = {

  en: {
    /* ── Navigation / TOC ─────────────────────── */
    'toc.title':          'Contents',
    'nav.overview':       'Overview',
    'nav.latency':        'Latency Analysis',
    'nav.throughput':     'Throughput Analysis',
    'nav.runs':           'Per-Run Details',

    /* ── Page header ──────────────────────────── */
    'header.title':       'Performance Benchmark Report',
    'meta.model':         'Model',
    'meta.api_type':      'API Type',
    'meta.dataset':       'Dataset',
    'meta.generated_at':  'Generated at',

    /* ── Section headings ─────────────────────── */
    'section.overview':   'Overview',
    'section.latency':    'Latency Analysis',
    'section.throughput': 'Throughput Analysis',
    'section.runs':       'Per-Run Details',

    /* ── Card / sub-card titles ───────────────── */
    'card.basic_info':        'Basic Information',
    'card.perf_metrics':      'Detailed Performance Metrics',
    'card.best_config':       'Best Performance Configuration',
    'card.recommendations':   'Performance Recommendations',
    'card.run_summary':       'Run Summary',
    'card.percentile_dist':   'Percentile Distribution',
    'card.percentile_curves': 'Percentile Curves',
    'card.percentile_curves_token_lat': 'Percentile Curves — TTFT / TPOT / ITL',
    'card.per_request':       'Per-Request Details',

    /* ── Inline badge suffixes ──────────────────────────────────── */
    'badge.runs':     'runs',
    'badge.requests': 'requests',

    /* ── Footer ───────────────────────────────── */
    'footer.generated_by': 'Generated by',

    /* ── Tab labels (from Python / Jinja2) ─────── */
    'Latency':            'Latency',
    'TTFT':               'TTFT',
    'TPOT':               'TPOT',
    'Request Throughput': 'Request Throughput',
    'Token Throughput':   'Token Throughput',
    'Success Rate':       'Success Rate',
    'Tokens':             'Tokens',
    'ITL':                'ITL',
    'TTFT / TPOT / ITL':  'TTFT / TPOT / ITL',
    'Success':            'Success',
  },

  zh: {
    /* ── Navigation / TOC ─────────────────────── */
    'toc.title':          '目录',
    'nav.overview':       '概览',
    'nav.latency':        '延迟分析',
    'nav.throughput':     '吞吐量分析',
    'nav.runs':           '运行详情',

    /* ── Page header ──────────────────────────── */
    'header.title':       '性能基准测试报告',
    'meta.model':         '模型',
    'meta.api_type':      'API 类型',
    'meta.dataset':       '数据集',
    'meta.generated_at':  '生成时间',

    /* ── Section headings ─────────────────────── */
    'section.overview':   '概览',
    'section.latency':    '延迟分析',
    'section.throughput': '吞吐量分析',
    'section.runs':       '运行详情',

    /* ── Card / sub-card titles ───────────────── */
    'card.basic_info':        '基本信息',
    'card.perf_metrics':      '详细性能指标',
    'card.best_config':       '最佳性能配置',
    'card.recommendations':   '性能建议',
    'card.run_summary':       '运行摘要',
    'card.percentile_dist':   '百分位分布',
    'card.percentile_curves': '百分位曲线（延迟）',
    'card.percentile_curves_token_lat': '百分位曲线（TTFT / TPOT / ITL）',
    'card.per_request':       '每请求详情',

    /* ── Inline badge suffixes ────────────────── */
    'badge.runs':     '轮',
    'badge.requests': '个请求',

    /* ── Footer ───────────────────────────────── */
    'footer.generated_by': '由以下工具生成',

    /* ── Tab labels (from Python / Jinja2) ─────── */
    'Latency':            '延迟',
    'TTFT':               '首 Token 时间',
    'TPOT':               '每 Token 时间',
    'Request Throughput': '请求吞吐量',
    'Token Throughput':   'Token 吞吐量',
    'Success Rate':       '成功率',
    'Tokens':             'Token 数',
    'ITL':                'Token 间延迟',
    'TTFT / TPOT / ITL':  '首Token/每Token/Token间延迟',
    'Success':            '请求成功率',
  },

}; /* end I18N */
